import { Input, Textarea } from "@nextui-org/react";
import type { NextPage } from "next";
import { TbCameraPlus as CameraPlus } from "react-icons/tb";
import Head from "next/head";
import Card from "../components/Card";
import { ProfilePictureUpload } from "../components/FileInputs";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>0xSub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Card></Card>
      </Layout>
    </div>
  );
};

export default Home;
